# Database properties
spring.application.name=Job-Portal
spring.datasource.url=jdbc:mysql://localhost:3306/jobPortal_db
spring.datasource.username=root
spring.datasource.password=@Muskan19
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Email Properties
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = work.muskan830@gmail.com
spring.mail.password = fundbmpjvsywarle
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true


# Environment variables
USER_FOUND = User has already registered.
USER_NOT_FOUND = User is not registered.
INVALID_CREDENTIALS = Invalid credentials.
OTP_NOT_FOUND = OTP is expired.
INVALID_OTP = Invalid OTP.
 